swagger: "2.0"
info:
  version: "1.0.0"
  title: "Job Portal"
host: "localhost:8081"

basePath: "/"
tags:
- name: "candidate"
  description: "API for candidate"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "recruiter"
  description: "API for recruiter"
- name: "ADMIN"
  description: "Admin to access all candidates and recrutier"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /candidate:
    post:
      tags:
      - "candidate"
      summary: "login or add new candidate"
      description: ""
      operationId: "LoginorAddcandidate"
      consumes:
      - "application/json"
      produces:
      - "text/plain"
      parameters:
      - in: "body"
        name: "body"
        description: "object of user to be logged in or added"
        schema:
          $ref: "#/definitions/candidate"
      responses:
        200:
          description: "Successfully login or add candidate"
        400:
          description: "Invalid input"
        401:
          description: "invalid id token"
          
  /candidate/{id}:
    get:
      tags:
      - "candidate"
      summary: "Display candidate details for given id"
      description: ""
      operationId: "candidateprofile"
      produces:
      - "text/plain"
      parameters:
      - in: "path"
        name: "id"
        type: integer
        required: true
        description: "Id token of logged in user"
      responses:
        200:
          description: "Return Details about candidate"
        401:
          description: "invalid id token"
  /candidate/{id}/jobs:
    get:
      tags:
      - "candidate"
      summary: "Display open jobs published by recruiter"
      description: ""
      operationId: "jobsforcandidate"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "id"
        type: integer
        required: true
      responses:
        200:
          description: "Return jobs"
        401:
          description: "invalid id token"
  /recruiter:
    post:
      tags:
      - "recruiter"
      summary: "login or add new recruiter"
      description: ""
      operationId: "LoginorAddrecruiter"
      consumes:
      - "application/json"
      produces:
      - "text/plain"
      parameters:
      - in: "body"
        name: "body"
        description: "object of user to be logged in or added"
        schema:
          $ref: "#/definitions/recruiter"
      responses:
        200:
          description: "Successfully login or add recruiter"
        400:
          description: "Invalid input"
        401:
          description: "invalid id token"
          
  /recruiter/{id}:
    get:
      tags:
      - "recruiter"
      summary: "Display recruiter details for given id"
      description: ""
      operationId: "recruiterprofile"
      produces:
      - "text/plain"
      parameters:
      - in: "path"
        name: "id"
        type: integer
        required: true
        description: "Id token of logged in user"
      responses:
        200:
          description: "Return Details about recruiter"
        401:
          description: "invalid id token"
  /recruiter/{id}/jobs:
    get:
      tags:
        - "recruiter"
      summary: "Display jobs published by recruiter for given id"
      description: ""
      operationId: "jobsbyrecruiter"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "id"
        type: integer
        required: true
      responses:
        200:
          description: "Return jobs"
        401:
          description: "invalid id token"
    post:
      tags:
        - "recruiter"
      summary: "Post a job"
      description: ""
      operationId: "insertrecruiter"
      consumes:
      - "application/json"
      produces:
      - "text/plain"
      parameters:
      - in: "path"
        name: "id"
        type: integer
        required: true
      - in: body
        name: body
        schema:
          $ref: '#/definitions/jobs'
      responses:
        200:
          description: "Return jobs"
        400:
          description: "invalid job parameter"
        401:
          description: "invalid id token"
      
          
definitions:
  jobs:
    type: object
    properties:
      jobid:
        type: number
      name:
        type: string
      salary:
        type: number
      department:
        type: string
      availabilty:
        type: number
      joining_date:
        type: number
        format: date
      skills:
        type: array
        items:
          type: string
      priority:
        type: array
        items:
          type: number
      
    
    
    
  details:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
      first_name:
        type: "string"
      last_name:
        type: "string" 
      gender:
        type: "string"
        enum:
        - "Male"
        - "Female"
      phone_number:
        type: "number"
        pattern: '^\+\d{1,3} \d{3} \d{3} \d{4}$'
    required:
      - username
      - password
      
      
  candidate:
    type: "object"
    properties:
      skills:
          type: array
          items:
            type: string
    allOf: 
      - $ref: '#/definitions/details'
      
      
  recruiter:
    type: "object"
    properties:
      company:
        type: string
    allOf:
      - $ref: '#/definitions/details'
